classdef batch
    properties (Constant)
        batteries = struct('policy', ' ', 'barcode', ' ', 'cycles', ...
            struct('discharge_dQdVvsV', struct('V', [], 'dQdV', []), ...
            'QvsT', struct('T', [], 'Q', []), 'NvsQ', struct('N', [], ...
            'Q', []), 'TvsQ', struct('T', [], 'Q', [])), ...
            'summary', struct('cycle', [], 'QDischarge', [], 'QCharge', ...
            [], 'IR', [], 'Tmax', [], 'Tavg', [], 'Tmin', [], ...
            'chargetime', []));
        contour_plot = [];
    end
    methods
    end
end